configuration:
  swagger:
    app: 'BeMyTech'
    description: 'BeMyTech website'
    developer: 'Sara Nalo'
    email: 'sara.nalo@stu.ibu.edu.ba'
  mailsender:
    default: 'sendgrid'

spring:
  data:
    mongodb:
      uri: mongodb+srv://saranalo:AQlXNTKpoufi6zQJ@bmt.6xnqrro.mongodb.net/?retryWrites=true&w=majority
      database: BMT

security:
  jwt:
    secret: 'QTcxvcLS0IR3JFLLkvMOBvXCde7DB8lKCnMMGOyI59s'