configuration:
  swagger:
    app: 'BeMyTech'
    description: 'BeMyTech website'
    developer: 'Sara Nalo'
    email: 'sara.nalo@stu.ibu.edu.ba'
  mailsender:
    default: 'mailgun'

spring:
  data:
    mongodb:
      uri: mongodb+srv://saranalo:AQlXNTKpoufi6zQJ@bmt.6xnqrro.mongodb.net/?retryWrites=true&w=majority
      database: BMT

email:
  mailgun:
    domain: https://api.mailgun.net/v3/sandbox5b75a339780841dc934b54cd16ab2801.mailgun.org
    from-email: BMT WebShop <mailgun@sandbox5b75a339780841dc934b54cd16ab2801.mailgun.org>
    username: api
    password: 66e42eb02e266587b3ba8cdf3d615fcc-69a6bd85-700f74d5

security:
  jwt:
    secret: 'QTcxvcLS0IR3JFLLkvMOBvXCde7DB8lKCnMMGOyI59s'

management:
  security:
    enabled: false

